id: IDAF62433
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T01:29:53+00:00'
last_modified: '2022-06-08T05:25:43.464337+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105875
  title: བོད་ཀྱི་སྐད་ཡིག་གསོ་སྦྱོང་སློབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2252':
      image_group_id: I1PD105877
      title: ''
      total_pages: 326
      order: 1
      base_file: 2252.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
